config:
  phases:
    - duration: 10
      arrivalCount: 5
      name: Warm Up
    - duration: 1
      arrivalCount: 10
      name: Spike
  environments:
    dev:
      target: "wss://q6gjgdgowf.execute-api.eu-west-3.amazonaws.com/dev"
      processor: "./index-dev.js" 
    prod:
      target: "wss://bwrmehhjm1.execute-api.eu-west-3.amazonaws.com/prod"
      processor: "./index-prod.js"