# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Publish the latest test version to the Google Play Store"
  lane :publish do
    ensure_env_vars(
      env_vars: ["SUPPLY_JSON_KEY_DATA"]
    )

    alpha_tracks = google_play_track_version_codes(
      track: "alpha",
      package_name: "com.awa.ma.dev.app",
    )

    if alpha_tracks.empty?
      puts "No alpha track to promote."
      next
    end

    puts "Will promote from alpha to production track #{alpha_tracks[0]}"
    supply(
      package_name: "com.awa.ma.dev.app",
      version_code: alpha_tracks[0],
      track_promote_to: "production",
    )
  end

  desc "Verify the version is highter than the latest in the Google Play Store"
  lane :verify_version do
    ensure_env_vars(
      env_vars: ["SUPPLY_JSON_KEY_DATA"]
    )

    alpha_tracks_version_codes = google_play_track_version_codes(
      track: "production",
      package_name: "com.awa.ma.dev.app",
    )

    alpha_tracks_release_names = google_play_track_release_names(
      track: "production",
      package_name: "com.awa.ma.dev.app",
    )

    puts "Version Codes"
    puts alpha_tracks_version_codes.inspect
    puts "Release Names"
    puts alpha_tracks_release_names.inspect

    # get pubspec
    pubspec = YAML.load_file("../../pubspec.yaml")

    pubspec_version = pubspec["version"]
    puts "Pubspec version"
    puts pubspec_version

    # if Gem::Version.new(pubspec["version"]) <= Gem::Version.new(lane_context[SharedValues::LATEST_VERSION])
    #   puts "Latest version is ??? but you try to push #{pubspec["version"]}"
    # else
    #   puts "Latest version is ??? and you push #{pubspec["version"]}"
    # end
  end
end