workflows:
  default-workflow:
    name: Default Workflow
    working_directory: chat-application
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'automatic-build'
          include: true
          source: true
    when:
      changeset:
        includes:
          - 'chat-application/'
        excludes:
          - '**/*.md'
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
        - google_play
        - other
        - ios_config
        - certificate_credentials
        - custom_networking
      flutter: default
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Set up key properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          flutter build appbundle --release \
            --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1)) \
            --dart-define="WEBSCOKET_ENDPOINT=$PRODUCTION_WEBSCOKET_ENDPOINT" \
            --dart-define="NOTIFICATION_HTTP_ENDPOINT=$PRODUCTION_NOTIFICATION_HTTP_ENDPOINT"
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Set up Provisioning profiles from environment variables
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${CM_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"  
      - name: Set up signing certificate
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist \
            --dart-define="WEBSCOKET_ENDPOINT=$PRODUCTION_WEBSCOKET_ENDPOINT" \
            --dart-define="NOTIFICATION_HTTP_ENDPOINT=$PRODUCTION_NOTIFICATION_HTTP_ENDPOINT"
    artifacts:
      - ./build/**/outputs/apk/**/*.apk
      - ./build/**/outputs/bundle/**/*.aab
      - ./build/**/outputs/**/mapping.txt
      - ./build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ./*.snap
      - ./build/windows/**/*.msix
      - ./flutter_drive.log
    publishing:
      email:
        recipients:
          - adrien.kaczmarek@gmail.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        in_app_update_priority: 0
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
