flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 100%
  individual_flags:
    - name: chat-backend
      paths:
        - chat-backend/
    - name: chat-application
      paths:
        - chat-application/