# This is a workflow to check syntax on JavaScript

name: Flutter Application Linter

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

# Jobs
jobs:
  flutter-application-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Install packages
        working-directory: ./chat-application
        run: flutter pub get
      - name: Run linter
        working-directory: ./chat-application
        run: flutter analyze --no-fatal-infos